### ISSUE TITLE
[Epic] Java low level client

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#1051]
### July release

- [x] Pagination support in protocol methods #1034
- [x] Use `RequestOptions` in protocol methods #1045 
- [x] Use RestProxy for protocol methods #1058 

### August release
- [ ] Test server tests https://github.com/Azure/autorest.java/issues/1065
- [x] Design LRO for protocol methods #1044
- [x] LRO implementation for protocol methods #1046
- [x] Create a new annotation in azure-core that can be used for protocol methods #1049
- [x] Support partial updates to Java file to replace/update generated protocol methods #1050
- [x] Generate API review for Purview on apiview.dev & Release (qwordy)

### September release (GA)
- [x] Support `StreamResponse` #1059
- [ ] Support `form-data` #1072
