### ISSUE TITLE
Fluent example generation

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1077]
- [x] collection method
- [x] resource create flow
- [x] resource update flow
- [x] handle polymorphic
- [x] handle Object type
- [x] generate SAMPLE.md
- [x] handle additional properties
- [x] handle parameter serialization, e.g. `collectionFormat=csv` and `collectionFormat=multi`

**Comment by weidongxu-microsoft** [comment]
resource create
https://github.com/Azure/autorest.java/pull/1074
https://github.com/Azure/autorest.java/pull/1075

**Comment by weidongxu-microsoft** [comment]
polymorphic
https://github.com/Azure/autorest.java/pull/1076

**Comment by weidongxu-microsoft** [comment]
Object
https://github.com/Azure/autorest.java/pull/1078

**Comment by weidongxu-microsoft** [comment]
SAMPLE.md
https://github.com/Azure/autorest.java/pull/1080

**Comment by weidongxu-microsoft** [comment]
resource update
https://github.com/Azure/autorest.java/pull/1082

**Comment by weidongxu-microsoft** [comment]
sample for Premium
https://github.com/Azure/autorest.java/pull/1134

**Comment by weidongxu-microsoft** [comment]
collectionFormat https://github.com/Azure/autorest.java/pull/1128

**Comment by weidongxu-microsoft** [comment]
additionalProperties https://github.com/Azure/autorest.java/pull/1153
