### ISSUE TITLE
Model generation for DPG from CADL

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1520]
- [ ] [Generate models required for specific operations in REST API](https://github.com/Azure/autorest.java/issues/1521)
- [x] [Generate models with enum properties](https://github.com/Azure/autorest.java/issues/1522)
- [x] Generate models with nullable properties
- [x] [Generate models with read-only properties](https://github.com/Azure/autorest.java/issues/1523)
- [x] [Generate models with optional properties](https://github.com/Azure/autorest.java/issues/1524)
- [x] [Generate models with properties of type boolean, string, byte, int, long, double, datetime, duration, array and map](https://github.com/Azure/autorest.java/issues/1525)
- [x] [Generate models with required properties](https://github.com/Azure/autorest.java/issues/1526)
- [x] [Generate models with constants](https://github.com/Azure/autorest.java/issues/1527)
- [x] [Generate polymorphic models](https://github.com/Azure/autorest.java/issues/1528)
- [x] [Do not generate error model if it matches the ResponseError structure](https://github.com/Azure/autorest.java/issues/1529)
