### ISSUE TITLE
Patch operation supoprt, Generate models with nullable properties for patch operations

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1530]
Use `Option<T>` in azure-core to generate models that support nullable properties in patch operations.

https://github.com/anuchandy/azure-sdk-for-java/blob/patch-model-example/sdk/metricsadvisor/azure-ai-metricsadvisor/src/main/java/com/azure/ai/metricsadvisor/patch/models/AnomalyDetectionConfigurationPatch.java

Generated sdk design:
https://github.com/srnagar/azure-sdk-for-java/tree/loadtesting-patch

Codegen tasks listed below:
```[tasklist]
### Tasks
- [x] Set stream-style-serialization=true for all models and check gaps
- [ ] https://github.com/Azure/autorest.java/issues/2396
- [x] Emitter: Add json-merge-patch into model usage
- [x] JsonMergePatchHelper: Add Helper class to get/set accessors
- [x] Model: Add jsonMergePatch flag and related static block to set flag
- [x] Model: Add updatedProperties map and the setters
- [x] Model: serialization and deserialization, `toJson()` and `toJsonMergePatch()`
- [x] Client: client method change on calling Helper
- [x] Client: support patch on optional body
- [x] Emitter: remove the code to disable convenient method for json-merge-patch, when convenientAPI=false, no need to add json-merge-patch handling
- [x] Client: use BinaryData.toBytes() to fire serialization
- [x] Emitter: turnoff convenient method for json-merge-patch if stream-style-serialization is disabled
- [x] cadl-ranch tests
- [ ] https://github.com/Azure/autorest.java/issues/2468
- [ ] https://github.com/Azure/autorest.java/issues/2471
```

**Comment by anuchandy** [comment]
Hi @srnagar, as discussed, posting the related gist here (its a bit old but probably useful for this work) https://gist.github.com/anuchandy/ca914f4a8dfaa49ea8e082de7e619c8f

**Comment by anuchandy** [comment]
Also a PPT on merge-patch+json and json-patch+json
[JsonMergePatch.pptx](https://github.com/Azure/autorest.java/files/8960834/JsonMergePatch.pptx)

**Comment by weidongxu-microsoft** [comment]
5. All the model that used by the PATCH model would be also a PATCH model.

**Comment by weidongxu-microsoft** [comment]
PS: the method (vanilla or convenience) is not in the scope of the DPG.

**Comment by weidongxu-microsoft** [comment]
still waiting for arch design

**Comment by haolingdong-msft** [comment]
Design doc from Srikanta: https://gist.github.com/srnagar/8ffc8d62f97be553bdb4edd775ed12d9

**Comment by haolingdong-msft** [comment]
8-16 Meeting minutes:
1. `isFieldUpdated()` will be package-private method handled by core.
1. What is the logic of `isFieldUpdated()`? 
Generated model will have a `Map` to trace which properties are set, which are not, and the setters will update the map. The map will also be passed to `isFieldUpdated()` as a parameter. Codegen will generate the map, setters and the logic to update the map.
2. When a model is shared by PUT and PATCH operation, and one property is required in PUT, but optional in PATCH, how to determine if the property is updated to null or it's because it's optional? 
We will put the properties into constructor which in both PUT and PATCH they are required, and let the service validate and throw error in PUT for the case where a property in PUT is required, but in PATCH is optional.

**Comment by lirenhe** [comment]
cc @mikekistler

**Comment by mikekistler** [comment]
One more question:
- How will `fromJson` initialize the map for `isFieldUpdated`? I assume that all fields will show as not updated, just as for the constructor.

**Comment by haolingdong-msft** [comment]
Hi @mikekistler, we discuss it in our DPG meeting with @srnagar. We can think of below scenarios of using `fromJson`
1. it is used when deserialize the response. In this case, constrctor will initialized the map, when the user call setters, the map will get updated.
2. it is used by customer directly and pass in a json to create a model, then we don't know if a field is mean to set to `null` or it's optional. But this case is very rare as if the user wants to pass in a json, he/she should use protocol method and does not interact with the models.

**Comment by haolingdong-msft** [comment]
loadtesting branch from Srikanta: https://github.com/srnagar/azure-sdk-for-java/tree/loadtesting-patch

**Comment by haolingdong-msft** [comment]
patch tsp design: https://github.com/Azure/typespec-azure/issues/3688

**Comment by haolingdong-msft** [comment]
Link stream-style-serialization bug fix: https://github.com/Azure/autorest.java/issues/2396

**Comment by haolingdong-msft** [comment]
cadl-ranch pr: https://github.com/Azure/cadl-ranch/pull/485
