### ISSUE TITLE
[MPG][Java] Unify CodeGen - Model

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.java#2330]
```[tasklist]
### Tasks
- [x] Codegen workflow for MPG using ServiceNetworking
- [x] Verify DPG tests all pass
- [x] Support LRO operations generation
- [x] Investigate on Pagination response name difference(OperationListResult vs PagedOperation)
- [x] Operation group null
```

**Comment by weidongxu-microsoft** [comment]
Do you plan 1 JAR or 2 JAR?

**Comment by XiaofeiCao** [comment]
Do you mean how many JARs we should pack into `typespec-java` (as I assume in npm/github we only release one artifact `@azure-tools/typespec-java`, similar to[ `@azure-tools/typespec-autorest`](https://github.com/Azure/azure-rest-api-specs/blob/8783ae52b1833aebc6d9679da9246d543b9856ff/specification/servicenetworking/ServiceNetworking.Management/tspconfig.yaml#L2))?

Currently I prefer doing it in one(azure-typespec-extension-jar-with-dependencies.jar). 
Reason is that we already have separate modules for FluentGen and JavaGen to have separate logics for dpg and mgmt. And since we share the same code model, there shouldn't be too many additional code in `typespec-extension`(JavaSettings and Main logics).

Do you have additional concerns?

**Comment by weidongxu-microsoft** [comment]
Yeah (in autorest we had 4 JAR).

Sure, I am fine with 1 JAR. Note that some code might get affected (since previously JAR is separated, so there is no need to do `isFLuent` check in fluent module).

If you have the code together, in some case, it would need that check now. e.g. https://github.com/Azure/autorest.java/blob/main/fluentgen/src/main/java/com/azure/autorest/fluent/FluentGen.java#L73-L75

I don't know how many there are, and that is the reason I want to to try these solutions early.

**Comment by weidongxu-microsoft** [comment]
Also the google-format is different...

**Comment by weidongxu-microsoft** [comment]
So I guess you first need to try switch the dependency to fluentnamer and fluentgen (from preproseccor and javagen).

**Comment by XiaofeiCao** [comment]
> since previously JAR is separated, so there is no need to do isFLuent check in fluent module, as it won't be in javagen JAR

Got it, thanks. If that's the case, I think we need separate JARs.

**Comment by XiaofeiCao** [comment]
I'm going to add a separate module for fluentgen, not sure about its name, `typespec-fluent`? 

In emitter, will invoke specific JAR according to whether its mgmt or dpg(may need to check how to identify it from tsp compiler's output).

**Comment by weidongxu-microsoft** [comment]
I guess you may try a single JAR first. See how it works for DPG. We had enough tests to verify that.
