### ISSUE TITLE
Enable stream-style-serialization for TypeSpec

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2396]
PR: https://github.com/Azure/autorest.java/pull/2398
CI : https://github.com/Azure/autorest.java/pull/2398/checks?check_run_id=18553581122

```[tasklist]
### Tasks
- [x] Support Enum contains long/double deserialization
- [ ] `ResponseError` deserialization
- [x] `DateTimeRfc7231` deserialization
- [x] `Base64Url` array deserialization
- [x] `Base64Url` bytes deserialization
- [x] `Double` to `Duration` deserialization
```

**Comment by haolingdong-msft** [comment]
PR: https://github.com/Azure/autorest.java/pull/2398
CI failures: https://github.com/Azure/autorest.java/pull/2398/checks?check_run_id=18553581122
1. Support Enum contains long/double deserialization
`XXXEnum.fromString()`
![image](https://github.com/Azure/autorest.java/assets/87355844/7355613e-656e-4651-8886-b6c538e4ad89)
https://github.com/Azure/autorest.java/blob/b09fa4856b972a84c0add9296a7d8e087ff71107/typespec-tests/src/main/java/com/cadl/enumservice/models/Operation.java#L260
Root cause:
In the `EnumType.java` it uses `getString()` which will have this compilation error.
https://github.com/Azure/autorest.java/blob/b09fa4856b972a84c0add9296a7d8e087ff71107/javagen/src/main/java/com/azure/autorest/model/clientmodel/EnumType.java#L168

2. `ResponseError` deserialization
![image](https://github.com/Azure/autorest.java/assets/87355844/63fc3691-9ce2-41e6-b5bf-5e5734a6740a)
https://github.com/Azure/autorest.java/blob/b09fa4856b972a84c0add9296a7d8e087ff71107/typespec-tests/src/main/java/com/cadl/errormodel/models/Diagnostic.java#L98
Root cause:
`ResponseError` does not support stream style serialization.
![image](https://github.com/Azure/autorest.java/assets/87355844/6c7fe6aa-b99f-49b4-9631-f11ce3b24b51)

3. `DateTimeRfc7231` deserialization
![image](https://github.com/Azure/autorest.java/assets/87355844/d4935a73-4173-40a7-af3b-258b63313423)

https://github.com/Azure/autorest.java/blob/b09fa4856b972a84c0add9296a7d8e087ff71107/typespec-tests/src/main/java/com/cadl/wiretype/models/SubClass.java#L84

4. `Base64Url` array deserialization
![image](https://github.com/Azure/autorest.java/assets/87355844/f71dae2a-60e7-4db9-8053-433a603b99be)
https://github.com/Azure/autorest.java/blob/b09fa4856b972a84c0add9296a7d8e087ff71107/typespec-tests/src/main/java/com/encode/bytes/models/Base64UrlArrayBytesProperty.java

5. Base64Url bytes deserialization
![image](https://github.com/Azure/autorest.java/assets/87355844/210fe2c4-a1d2-4c3a-b99d-0da476b6558a)
https://github.com/Azure/autorest.java/blob/b09fa4856b972a84c0add9296a7d8e087ff71107/typespec-tests/src/main/java/com/encode/bytes/models/Base64UrlBytesProperty.java

6. Support double array deserialization
![image](https://github.com/Azure/autorest.java/assets/87355844/31dc680b-e4ef-4c15-91ac-dfee4f8c9668)
https://github.com/Azure/autorest.java/blob/b09fa4856b972a84c0add9296a7d8e087ff71107/typespec-tests/src/main/java/com/encode/duration/models/FloatSecondsDurationArrayProperty.java#L79
