### ISSUE TITLE
mpg, initial functional version

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2422]
ApiView diff: https://apiview.dev/Assemblies/Review/a5478a8310b64355af6237d9e06c63c1?revisionId=56db5905a50e4d69b80d25d184d528bb&diffOnly=False&doc=False&diffRevisionId=47b359ec7aa94def8e7b89a06234bfda

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.java/issues/2520
- [ ] https://github.com/Azure/autorest.java/issues/2518
- [ ] https://github.com/Azure/autorest.java/issues/2519
- [ ] https://github.com/Azure/autorest.java/issues/2487
- [ ] https://github.com/Azure/autorest.java/issues/2505
- [ ] when resource's update method is non-LRO, `apply` method will have wrong implementation
- [ ] https://github.com/Azure/autorest.java/issues/2484
- [ ] https://github.com/Azure/autorest.java/issues/2503
- [ ] https://github.com/Azure/autorest.java/issues/2481
- [x] `listBySubscription` and `get` need to be renamed to `list` and `getByResourceGroup`.
- [x] `listNext` is generated in resource collections(hardcoded)
- [x] Identify `subscriptionId` parameter in emitter. (hardcoded)
- [x] `TrackedResource(Base)`, `ProxyResource(Base)`, `ArmResource` shouldn't be generated. (hardcoded)
- [x] xxResourceProperties seems to be modeled as resource.
- [x] ParentResource not correctly identified, e.g. Association should be child of TrafficController
- [x] define/list/get/deleteById is removed from `AssociationInterfaces`(resource collection).
```

**Comment by weidongxu-microsoft** [comment]
Could you prioritize the 1st one? I could not imagine how this could happen. Resource must have id+type+name.

**Comment by XiaofeiCao** [comment]
Sure. 

I saw in generated code, that these resources like `AssociationInner` now extends newly generated model `TrackedResourceBase`, instead of `Resource`. This is not correct.

**Comment by weidongxu-microsoft** [comment]
There is lots of processing on schema (and its parent schema) in https://github.com/Azure/autorest.java/blob/main/fluentnamer/src/main/java/com/azure/autorest/fluent/transformer/ResourceTypeNormalization.java

Maybe this be the cause (as class hierarch is now different; previously it should only be subclass of `TrackedResource`)

**Comment by XiaofeiCao** [comment]
For identifying model as resource, there are probably two ways to handle this.

1. We handle it in emitter code, use library method `getArmResourceKind` from `typespec-azure-resource-manager` and rename parent model names accordingly, e.g. `TrackedResourceBase` -> `TrackedResource`.
2. We handle it in codegen code, modify `ResourceTypeNormalization`. 

I'll go with 1 since we can directly use library API, in case resource identifying implementation has changed.

**Comment by weidongxu-microsoft** [comment]
some of them maybe cross-language.

e.g. 
1. subscriptionId -> add `isSubscriptionId` method in TCGC (similar to the current `isApiVersion`)?
2. endpoint/host
