### ISSUE TITLE
tsp, support json-merge-patch for model with required properties

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2471]
**Case:**

Consider the case of shared model between PUT and Json-Merge-Patch e.g.
```
model SharedModel {
  requiredProp1: string,
  requiredProp2: int32,
  innerModel: InnerModel,
  optionalProp3?: ...
}
```
And how we'd like the class be. Think e.g. what user need to do on the patch, when they only want to modify requiredProp1

Design discussion needed, as current required properties are all set in constructor and do not have setters.

Note: we have one [RFC item](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#rest-response-body-is-resource-schema) saying patch operation's model should not contain required properties. typespec-autorest will create another model named `XXXCreateOrUpdate` to make all the properties optioanl. This is not done by compiler, compiler will not return the model `XXXCreateOrUpdate`.
[playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvdmVyc2lvbmluZyI7CskfYXp1cmUtdG9vbHMvyCstxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLlJlc3Q70BVIdHRw0RVWyXLIG0HEWS5Db3JlLlRyYWl0czsKCkBzZXJ2aWNlKHt0aXRsZTogIlRleHQgYXV0aG9y5ACufSkKQOcAvWVkKFPGLsdccykKbmFtZXNwYWNlIMQ4Qcg3OwoKZW51bSDPMCB7CiAgQHVzZURlcGVuZGVuY3ko6wCWyCcudjFfMF9QcmV2aWV3XzIpCiAgdjE6ICIyMDIxLTDEAyIsCn0KCmludGVyZsR9UmVzb3VyY2VPcGVyYXTERAogIGV4dGVuZHPsAPjSKDxOb1JlcGVhdGFibGVSZXF1ZXN0cyAmIE5vQ29uZGnEJGFszhhsaWVudMcTSWQ%2BIHt9CgpAcsdaKCJwcm9qZWN0cyIpCm1vZGVsIFDGEeYA%2FWtlecQHdmlzaWJpbGl0eSgicmVhZCLkAOVpZDogc3TmAUAgIGRlc2NyaXDkAII%2FyhgKICDkAXTKEe0BCOkBgcVtbGlzdCBpc%2FMBHukBCUNyZWF0ZU9yVXBkYXRlPOcAqz7EVw%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D)

**Design questions：**
1. Do we want to refer autorest-typespec? ie. create another class to make all the fields as optional if the model is used by patch? But this is against round trip model, if we want to have **only one round trip model** to be used for both patch and put, we may need to add setters for all required properties? 
2. If user sets `null` for required field in constructor. Do we need to serialize null? Currently we can't do this even we have setters for required properties, because the `updatedProperties` map will not be updated in constructor, so during serialziation, the `null` cannot be serialized. [code](https://github.com/Azure/autorest.java/pull/2424/files#diff-caedf8a9547082abd40e6a262e3cfe440ae07fc33e851c2847ae5e1c271bccd0) [test](https://github.com/Azure/autorest.java/pull/2424/files#diff-f88bd438989662357eeebc5e606878e89076b7b6ec76017cf6a0148542602cb8)
```java
@Immutable
public final class StringProperty implements JsonSerializable<StringProperty> {
    @Generated
    public StringProperty(String requiredProperty, String nullableProperty) {
        this.requiredProperty = requiredProperty;
        this.nullableProperty = nullableProperty;
    }
}

public class Test {
  test(){
          StringProperty s = new StringProperty("foo", null);
          stringClient.patchNull(s);
  }
}
```
```[tasklist]
### Tasks
- [x] Throw error during serialization when map's key is null
- [x] make all property of patch model be optional and add ctor with no arg
- [x] bug fix: make `toJsonMergePatch()` as private
- [x] bug fix: switch the order of null checking and updateProperties` map checking
- [ ] support hierarchical model as patch model property. https://github.com/Azure/autorest.java/issues/2615
- [ ] deserialization called setter now, but should not. https://github.com/Azure/autorest.java/pull/2576#issuecomment-1966144039
```

**Comment by haolingdong-msft** [comment]
Preferred Option:
Have one default ctor with setters for all properties, nested models will also apply this way
Have javadoc to indicate if a property is required, javadoc at three levels: operation level, model level, model setters level
Let service throw error if the required property is not passed

**Comment by haolingdong-msft** [comment]
2024-2-8 meeting minutes:
1. we talked about why we only have one default ctor with no arguments, the reason is we want to make it explicit for user to call the setter, and we don't want to have two ctors to make the user confused on which one to use.
2. We should throw error when finding map's key is `null` during serialization.
3. we should only send properties that are updated to the backend, which means we first check if the properties are in updatedProperties map, then do null check.

**Comment by weidongxu-microsoft** [comment]
In client model impl, make all property of patch model be "required=false"
But add a "requiredForCreate", so that we can have a line in Javadoc saying that "Required when creating a resource".

**Comment by weidongxu-microsoft** [comment]
what's the remaining task about "required properties"?

**Comment by haolingdong-msft** [comment]
Hi @weidongxu-microsoft 
![image](https://github.com/Azure/autorest.java/assets/87355844/fa89f141-5119-4e44-9ed0-8828dbad20d2)
I previously add the two remaining issues from the PR to this issue, so I did not close it.
But I think we can create seperate issue and close this one. 
We already create issuse to support patch for polymorhic model. I may create another issue to not using setter when deserialize the model, and I can discuss with Alan on this.
Is it good for you?
