### ISSUE TITLE
dpg, integrate TCGC getAllModels - basic support

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2564]
TCGC `getAllModels()` code is already on main. We will need to `getAllModels()` in emitter to replace the logics in `processModels()`.

```[tasklist]
### Tasks
- [x] Check the type mapping from compiler Type to TCGC SDKType
- [x] Replace logics for `intrinsic` types. e.g. `unkonwn`, `void`, `never`, `any`
- [x] Replace logics for `enum` type, pay attention to the case on using union express extensible enum for unbranding
- [x] Replace logics for `union` type
- [x] Replace logics for `Record` type
- [x] Replace logics for `constant` type
- [x] Replace logics for `Array` type, pay attention to `byte` array
- [x] Replace logics for `Scalar` type, e.g. `number`, `decimal`, `string`, `boolean`, `bytes` etc. pay attention to format
- [x] Replace logics for `Model` type, basic cases
- [x] Replace logics for `Model` type, discriminator and inheritance' cases
- [x] Replace logics for `Model` type, additional properties
- [x] Replace logics for `Model` type, multipart form data cases
- [x] Pass all tests cases in typespec-tests/tsp and cadl-ranch
- [ ] https://github.com/Azure/autorest.java/issues/2728
- [ ] https://github.com/Azure/autorest.java/issues/2729
- [ ] https://github.com/Azure/autorest.java/issues/2730
- [ ] https://github.com/Azure/autorest.java/issues/2731
- [ ] https://github.com/Azure/autorest.java/issues/2732
```

Possible gaps between TCGC type and compiler type:
1. `unkown` type in compiler will be converted to `any` type in TCGC `SdkType`.
2. `void` and `never` is not supported in TCGC `SdkType` yet. TCGC issue: https://github.com/Azure/typespec-azure/issues/292
8. `SdkType` does not contain `namespace` information. https://github.com/Azure/typespec-azure/issues/290
9.  `SdkType.description` and `SdkType.detail`: If both `@summary` and `@doc` exist, .`description` will be the content in `@summary` and `detail` will be the content in `@doc`. If only `@doc` exists, then `description` will be the content in `@doc`.
10. TCGC types does not have concept of `@format`, it will map the type with `@format` to an `SdkBuiltInType`. (expected)
11. Optional literal do not have correct generated name. https://github.com/Azure/typespec-azure/issues/553
12. Description is not correctly returned for scalar types https://github.com/Azure/typespec-azure/issues/555
13. discriminator, Returned model properties are not correct when discriminator as @clientName decorator https://github.com/Azure/typespec-azure/issues/554
14. model is array case not handled correctly： https://github.com/Azure/typespec-azure/issues/690
1. Type of model property/enum member when it is defined as constant number: https://github.com/microsoft/typespec/issues/3314
2.  when should standalone models be generated: https://github.com/Azure/typespec-azure/issues/823
3. ARM breaking change on `UserAssignedIdentity`: https://github.com/Azure/typespec-azure/issues/825

**Comment by weidongxu-microsoft** [comment]
The Model is get from the raw Type. Use raw in it is meaningless.

**Comment by haolingdong-msft** [comment]
Type mapping from compiler `Type` to TCGC `SdkType` highlights:
1. `unkown` type in compiler will be converted to `any` type in TCGC `SdkType`.
2. `void` and `never` is not supported in TCGC `SdkType` yet.
3. `scalar` type in compiler will be converted to builtin types.
4. `Record` type in compiler will be converted to `dict` type in TCGC `SdkType`.

**Comment by lirenhe** [comment]
> The Model is get from the raw Type. Use raw in it is meaningless.

Please try to use the real models returned by TCGC instead of raw.  And we shall continue reducing the usage of 'raw' in the source code till it is no longer needed. 

cc @lmazuel

**Comment by weidongxu-microsoft** [comment]
> > The Model is get from the raw Type. Use raw in it is meaningless.
> 
> Please try to use the real models returned by TCGC instead of raw. And we shall continue reducing the usage of 'raw' in the source code till it is no longer needed.
> 
> cc @lmazuel

I was saying the same thing... "Use raw in it is meaningless."

**Comment by weidongxu-microsoft** [comment]
`never` means not exist. So it is correct that it not map to anything.

**Comment by weidongxu-microsoft** [comment]
You can start merging back to main branch, if you can handle Scalar and Model (they are 2 major ones)

**Comment by haolingdong-msft** [comment]
I agree, I will try to make the change incrementally and split to seperate mergable pr.

**Comment by haolingdong-msft** [comment]
[Loop page](https://loop.microsoft.com/p/eyJ3Ijp7InUiOiJodHRwczovL21pY3Jvc29mdC5zaGFyZXBvaW50LmNvbS8%2FbmF2PWN6MGxNa1ltWkQxaUlXMVFSQzFzTkZWeFgydFRVblJqVXpSbmQwZDZRazl3TFhGWWNHcHVNbkJCZFU5cVRXMVlOR2Q0YkZrellrZ3lWRWxmUkZkU1luRllhRXRqUkROcVgwUW1aajB3TVZSS1dGbFZWMU5QVmtSRVNrdEJRa3hTTlVOTE0waFBVbEpNVWxWSE1rcFJKbU05Sm1ac2RXbGtQVEUlM0QiLCJyIjpmYWxzZX0sInAiOnsidSI6Imh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQuY29tLzpmbDovci9zaXRlcy9iMWVmYzE4ZS1lZTZlLTRkN2YtODIzZS05MzZkOTAxNTMyMzAvU2hhcmVkJTIwRG9jdW1lbnRzL0xvb3BBcHBEYXRhL1VudGl0bGVkLmxvb3A%2FZD13MWM1ZjFiYTU2YWZkNDg4Y2I0NmE0N2NjYjVlNGY5ZjAmY3NmPTEmd2ViPTEmbmF2PWN6MGxNa1p6YVhSbGN5VXlSbUl4Wldaak1UaGxMV1ZsTm1VdE5HUTNaaTA0TWpObExUa3pObVE1TURFMU16SXpNQ1prUFdJaGJWQkVMV3cwVlhGZmExTlNkR05UTkdkM1IzcENUM0F0Y1Zod2FtNHljRUYxVDJwTmJWZzBaM2hzV1ROaVNESlVTVjlFVjFKaWNWaG9TMk5FTTJwZlJDWm1QVEF4VkVwWVdWVlhWa1pFVGxCU1dqZE1TMUpTUlV4Sk1sTklXbE15TmtvMlVGRW1ZejBsTWtZbVpteDFhV1E5TVNaaFBVeHZiM0JCY0hBbWNEMGxOREJtYkhWcFpIZ2xNa1pzYjI5d0xYQmhaMlV0WTI5dWRHRnBibVZ5Sm5nOUpUZENKVEl5ZHlVeU1pVXpRU1V5TWxRd1VsUlZTSGgwWVZkT2VXSXpUblphYmxGMVl6Sm9hR050Vm5kaU1teDFaRU0xYW1JeU1UaFphVVowVlVWUmRHSkVVbFpqVmpseVZURktNRmt4VFRCYU0yUklaV3RLVUdORE1YaFhTRUp4WW1wS2QxRllWbEJoYXpGMFYwUlNibVZIZUZwTk1rcEpUV3hTU2xnd1VsaFZiVXA0VjBkb1RGa3dVWHBoYkRsRlprUkJlRlpGY0ZsWFZsWllWVEE1VjFKRlVrdFRNRVpEVkVaSk1WRXdjM3BUUlRsVFZXdDRVMVpWWTNsVGJFVWxNMFFsTWpJbE1rTWxNakpwSlRJeUpUTkJKVEl5Tnpka1ptSm1NekF0TkRFMk15MDBNV1JtTFdFNE1XVXRZelk1WkdOalpEZG1PR05rSlRJeUpUZEUiLCJyIjpmYWxzZX0sImkiOnsiaSI6Ijc3ZGZiZjMwLTQxNjMtNDFkZi1hODFlLWM2OWRjY2Q3ZjhjZCJ9fQ%3D%3D)

**Comment by haolingdong-msft** [comment]
TCGC will deprecate `nullable` property on type. Only `property`, dictionary value and additional property has `nullable` property.
