### ISSUE TITLE
Implement TCGC's SdkPackage types

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#2665]
Language emitters should work to move entirely to TCGC's new ecosystem. The entry point for the ecosystem is accessing .sdkPackage on the SdkContext returned from tcgc

https://azure.github.io/typespec-azure/docs/howtos/DataPlane%20Generation%20-%20DPG/07tcgcTypes
```[tasklist]
### Tasks
- [x] Replace logics for process operation parameters
- [x] Replace logics for server parameters
- [x] Replace logics for process operation
- [x] Replace logics for process clients
- [x] Replace logics for process response
- [x] Replace logics for process LRO
- [x] Replace logics for process body parameters
- [x] Replace logics for process examples
- [x] Replace logics for process auth
- [x] Replace logics for the util functions, e.g. addAcceptedHeader, processEtagHeader etc.
- [x] Replace logics for versioning
- [ ] Integrate with access and usage
- [ ] Pass cadl-ranch and typespec-tests
- [x] integrate with new SdkClientType design
- [x] integrate with new multipart design
- [x] integrate with uri template
```

TCGC dependencies:
```[tasklist]
### TCGC dependency issues
- [ ] https://github.com/Azure/typespec-azure/issues/954
- [ ] https://github.com/Azure/typespec-azure/issues/917
- [ ] https://github.com/Azure/typespec-azure/issues/916
- [ ] https://github.com/Azure/typespec-azure/issues/963
- [ ] https://github.com/Azure/typespec-azure/issues/965
- [ ] https://github.com/Azure/typespec-azure/issues/980
- [ ] https://github.com/Azure/typespec-azure/issues/217
- [ ] https://github.com/Azure/typespec-azure/issues/1088
- [ ] https://github.com/Azure/typespec-azure/issues/1060
- [ ] https://github.com/Azure/typespec-azure/issues/1164
- [ ] https://github.com/Azure/typespec-azure/issues/1259
- [ ] https://github.com/Azure/typespec-azure/issues/1153
- [ ] https://github.com/microsoft/typespec/issues/4132
```

```[tasklist]
### TCGC dependency issues - continue.
- [ ] https://github.com/Azure/typespec-azure/issues/965
```

**Comment by haolingdong-msft** [comment]
Hi @iscai-msft @lmazuel, Java may need to start this work at June as we are working on remaining items related with TCGC model types in May. Please let me know if there is any concern.
https://github.com/Azure/autorest.java/issues/2728 (depends on TCGC to remove undefined value)
https://github.com/Azure/autorest.java/issues/2729 (depends on two issues listed)
https://github.com/Azure/autorest.java/issues/2732 (done)
https://github.com/Azure/autorest.java/issues/2730 (will adopt after TCGC released)
https://github.com/Azure/autorest.java/issues/2731 (in progress)

**Comment by haolingdong-msft** [comment]
First API view to show the API diff: https://apiview.dev/Assemblies/Review/e0cf256f814e456bac0f0d751bd4aa9f/81e4187324194e33899d9cbb375aeb4a?diffRevisionId=46902be02c1b4f0cbe9f89e2a5137a05&diffOnly=true

There are not much public API diff. Existing diffs are caused by three cases:
1. client structure case: The latest revision does not generate for cadl-ranch client structure case (https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/client/structure), as it has compile error, and depends on TCGC issue: https://github.com/Azure/typespec-azure/issues/1060
2. anonymous parameter name change: for flattened parameter (which is also anonymous model) case, if we use the name from TCGC, we will have generation error. So I did not use the parameter name from TCGC for anonymous model. 
3. ARM case's endpoint cannot be set: this is pending on TypeSpec team's fix. issue: https://github.com/Azure/typespec-azure/issues/217

**Comment by haolingdong-msft** [comment]
new version of api-view: https://apiview.dev/Assemblies/Review/e0cf256f814e456bac0f0d751bd4aa9f/6104eaa1d87b4b1bbfb474632fa7365e?diffRevisionId=46902be02c1b4f0cbe9f89e2a5137a05&diffOnly=true

**Comment by haolingdong-msft** [comment]
API view based on 7.11 main:
https://apiview.dev/Assemblies/Review/e0cf256f814e456bac0f0d751bd4aa9f/555f98a4f0254f81acf9f257841c83fe?diffRevisionId=b792a3ef67e044379ff8407f58c99dd1&diffOnly=True

**Comment by haolingdong-msft** [comment]
7.15 API view: 
https://apiview.dev/Assemblies/Review/e0cf256f814e456bac0f0d751bd4aa9f/99297657ec5a4c28a177ad9d3a984044?diffRevisionId=b792a3ef67e044379ff8407f58c99dd1&diffOnly=True

Public API diffs summary:

1. client structure case: The latest revision does not generate for cadl-ranch client structure case (https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/client/structure), as it has compile error, and depends on TCGC issue: https://github.com/Azure/typespec-azure/issues/1060
2. ARM case's endpoint cannot be set: this is pending on TypeSpec team's fix. issue: https://github.com/Azure/typespec-azure/issues/217
3. api version is added to builder when there are multiple servers - still wip on this.
4. operation group's client name change, caused by TCGC not consider `@clientName` to overwrite client name.

**Comment by haolingdong-msft** [comment]
Update for Meeting 8/1:

1. Finished the two follow up items from last meeting:
	• return type's response: Try to add logic in codegen to dislay response's desc, but have some issues remaining for handling ok response, file an issue first: https://github.com/Azure/autorest.java/issues/2878. Finish the logic to merge summary and description on return type to unblock sdkpackage adoption
	• optional body case: remove content type added by TCGC for optional body case


2. Issues fixed:
	• Override ARM endpoint param: work around from emitter side and regened, passed test, will adopt TCGC after Izzy made the change we agreed on this morning
	• Found the root cause for multiple server case diff, fixed  logics and wip regen to test

3. Integrage with latest TCGC changes:
	• Integrate with TCGC's filtered API version logics: finished and passed tests
       - Merge with multipart changes, found some unexpected diffs, checking now

**Comment by haolingdong-msft** [comment]
Update on 8/7:
latest API view: [com.azure.tools:azure-typespec-tests - apiview.dev](https://apiview.dev/Assemblies/Review/e0cf256f814e456bac0f0d751bd4aa9f/d2d206fc3c5d44db9135fbf261aa5392?diffRevisionId=e8c51901bc82471792b67e3b19771caf&diffOnly=true)

There are only two issues remaining. 
1. multipart (this depends on TCGC bug fix to be released)  https://github.com/Azure/typespec-azure/pull/1281
3. parameter order changes(maybe due to we adopt TCGC parameter spread feature, I am checking now)

**Comment by haolingdong-msft** [comment]
Update on 8/12:
latest API view: https://apiview.dev/Assemblies/Review/e0cf256f814e456bac0f0d751bd4aa9f/e0f4e0c3e4704de89332b6229b14ad64?diffRevisionId=fbdae726b3a04e839587766478ca88eb&diffOnly=true

The diff is all due to below:

<img width="763" alt="image" src="https://github.com/user-attachments/assets/b2378cb7-d1b6-4fb1-b392-827073831b85">


Another diff in impl: 
- TCGC has not supported allowReserved for path parameter yet, so I comment out the corresponding part of logic in emitter and add TODO https://github.com/Azure/autorest.java/commit/fc35d0fe3520cc668a6f2029a64284453d29874d.

**Comment by weidongxu-microsoft** [comment]
Order change on property may due to a PR by @XiaofeiCao -- could you take a look?

**Comment by XiaofeiCao** [comment]
> Order change on property may due to a PR by @XiaofeiCao -- could you take a look?
> 
> kind of like this https://github.com/Azure/azure-sdk-for-java/pull/41497/files

Yes, it is. I've replied in chat:

ARM diff is expected. It's a side-effect of a bug fix:
[fix, mgmt shadow properties from Resource/ProxyResource by XiaofeiCao · Pull Request #2905 · Azure/autorest.java (github.com)](https://github.com/Azure/autorest.java/pull/2905)
 
> generated code diffs are reordering of the shadowed properties(a side effect of the fix logic). Now properties from subclass will come before the ones from parent class.

**Comment by haolingdong-msft** [comment]
Java released emitter version 0.20.0 with sdkpackage adoption changes in:
https://www.npmjs.com/package/@azure-tools/typespec-java/v/0.20.0
I have also verified the diffs in SDK repo and the refreshed code in SDK repo.
https://github.com/Azure/azure-sdk-for-java/pull/41666
