### ISSUE TITLE
Epic: tsp, TCGC common layer adoption enhancements

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2931]
> Remaining issues that should be done after TCGC supports, TCGC dependency issue is listed in each issue.

### Already Done

- [x] `Sdkpackage` adoption: https://github.com/Azure/autorest.java/issues/2665
- [x] `SdkType` adoption: https://github.com/Azure/autorest.java/issues/2564

### Remaining Tasks
- [ ] https://github.com/Azure/autorest.java/issues/2912
- [x] https://github.com/Azure/autorest.java/issues/2913
- [x] https://github.com/Azure/autorest.java/issues/2920
- [ ] https://github.com/Azure/autorest.java/issues/2930
- [x] https://github.com/Azure/autorest.java/issues/2729
- [x] https://github.com/Azure/autorest.java/issues/2728
- [x] https://github.com/Azure/autorest.java/issues/2932
- [x] https://github.com/microsoft/typespec/issues/4394
- [x] https://github.com/Azure/autorest.java/issues/2974
- [ ] https://github.com/Azure/autorest.java/issues/2984

### TCGC dependencies
- [ ] https://github.com/Azure/typespec-azure/issues/1441
- [ ] https://github.com/Azure/typespec-azure/issues/1391
- [ ] https://github.com/Azure/typespec-azure/issues/1259

### TCGC dependencies for adopting access and usage
- [ ] https://github.com/Azure/typespec-azure/issues/1748
- [ ] https://github.com/Azure/typespec-azure/issues/1749
- [ ] https://github.com/Azure/typespec-azure/issues/1750
- [ ] https://github.com/Azure/typespec-azure/issues/1538
- [ ] https://github.com/Azure/typespec-azure/issues/1747
- [ ] https://github.com/Azure/typespec-azure/issues/1752

**Comment by haolingdong-msft** [comment]
TCGC usage and access case study: https://gist.github.com/haolingdong-msft/df3f25a048baf83d8fabf5206aacc7db
TCGC usage and access case study for spread cases: https://gist.github.com/haolingdong-msft/2d941f452551a6f96e141adbc38ac483
